//! Simplified Chinese presentation strings. Never translate PDF contents or command IDs.

pub const CHINESE: &[(&str, &str)] = &[
    ("Menu", "菜单"),
    ("File", "文件"),
    ("Edit", "编辑"),
    ("Pages", "页面"),
    ("View", "视图"),
    ("Help", "帮助"),
    ("Home", "首页"),
    ("All tools", "所有工具"),
    ("Remove watermarks", "水印去除"),
    ("Analyze watermarks", "分析水印"),
    ("Select and remove watermarks", "选择与删除水印"),
    ("Excel (text and tables)", "Excel（文字与表格提取）"),
    ("PPT (one page image per slide)", "PPT（每页一张图片）"),
    ("Multiple PDFs, images or text files", "多个 PDF、图片或文本"),
    ("Basic preflight (PDF/A)", "基础预检（PDF/A）"),
    ("Convert text and vectors to grayscale", "文字与矢量转灰度"),
    ("Convert", "转换"),
    ("Sign", "签名"),
    ("Read", "阅读"),
    ("Fill & Sign", "填写与签名"),
    ("Preferences", "偏好设置"),
    ("Preferences…", "偏好设置…"),
    ("Interface language", "界面语言"),
    ("Identity", "身份信息"),
    ("Name on new comments", "新批注的作者姓名"),
    ("Open…", "打开…"),
    ("Open file", "打开文件"),
    ("New blank PDF", "新建空白 PDF"),
    ("Create PDF from file…", "从文件创建 PDF…"),
    ("Create PDF from images…", "从图片创建 PDF…"),
    ("Create PDF from clipboard", "从剪贴板创建 PDF"),
    ("Combine files…", "合并文件…"),
    ("Save", "保存"),
    ("Save as…", "另存为…"),
    ("Close file", "关闭文件"),
    ("Close all", "全部关闭"),
    ("Revert", "恢复已保存的版本"),
    ("Print…", "打印…"),
    ("Document properties…", "文档属性…"),
    ("Document Properties", "文档属性"),
    ("Undo", "撤销"),
    ("Redo", "重做"),
    ("Find…", "查找…"),
    ("Advanced search…", "高级搜索…"),
    ("Copy pages", "复制页面"),
    ("Cut pages", "剪切页面"),
    ("Paste pages", "粘贴页面"),
    ("Fit visible", "适合可见区域"),
    ("Marquee zoom", "框选缩放"),
    ("Take a snapshot", "截取快照"),
    ("Full screen mode", "全屏模式"),
    ("Read mode", "阅读模式"),
    ("Switch light / dark theme", "切换浅色／深色主题"),
    ("Comments panel", "批注面板"),
    ("Form fields panel", "表单字段面板"),
    ("Bookmarks panel", "书签面板"),
    ("Pages panel", "页面面板"),
    ("Layers panel", "图层面板"),
    ("Attachments panel", "附件面板"),
    ("Signatures panel", "签名面板"),
    ("Clear form", "清空表单"),
    ("Find tools and commands…", "搜索工具和命令…"),
    ("Search tools and commands…", "搜索工具和命令…"),
    ("No matching tools", "没有匹配的工具"),
    ("Zoom", "缩放"),
    ("Actual size", "实际大小"),
    ("Zoom to page level", "适合整页"),
    ("Fit to width", "适合宽度"),
    ("Display theme", "显示主题"),
    ("Side panels", "侧边面板"),
    ("Enable Acrobat JavaScript", "启用 Acrobat JavaScript"),
    ("Light", "浅色"),
    ("Dark", "深色"),
    ("System", "跟随系统"),
    ("OK", "确定"),
    ("Cancel", "取消"),
    ("Apply", "应用"),
    ("Close", "关闭"),
    ("Add", "添加"),
    ("Remove", "移除"),
    ("Delete", "删除"),
    ("Clear", "清空"),
    ("Clear all", "全部清空"),
    ("Reset", "重置"),
    ("Done", "完成"),
    ("Next", "下一项"),
    ("Previous", "上一项"),
    ("Browse…", "浏览…"),
    ("Choose…", "选择…"),
    ("None", "无"),
    ("Yes", "是"),
    ("No", "否"),
    ("Ready", "可用"),
    ("Available", "可用"),
    ("NEW", "新"),
    ("Tool", "工具"),
    ("Command", "命令"),
    ("View less", "收起"),
    ("View more", "更多工具"),
    ("Back to all tools", "返回所有工具"),
    ("Close panel", "关闭面板"),
    ("Recommended tools", "常用工具"),
    ("Recent", "最近打开"),
    ("Use now", "立即使用"),
    ("Privacy", "隐私"),
    ("Export a PDF", "导出 PDF"),
    ("Edit a PDF", "编辑 PDF"),
    ("Create a PDF", "创建 PDF"),
    ("Combine files", "合并文件"),
    ("Organize pages", "整理页面"),
    ("Add comments", "添加批注"),
    ("Scan & OCR", "扫描与文字识别"),
    ("Protect a PDF", "保护 PDF"),
    ("Redact a PDF", "涂黑敏感信息"),
    ("Compress a PDF", "压缩 PDF"),
    ("Prepare a form", "准备表单"),
    ("Add a stamp", "添加印章"),
    ("Use a certificate", "证书与数字签名"),
    ("Use print production", "印刷制作"),
    ("Measure objects", "测量对象"),
    ("Compare files", "比较文件"),
    ("Use guided actions", "引导操作"),
    ("Prepare for accessibility", "辅助功能"),
    ("Apply PDF standards", "PDF 标准"),
    ("Add search index", "搜索索引"),
    ("Use JavaScript", "JavaScript 工具"),
    ("AI assistant", "AI 助手"),
    ("Export to", "导出为"),
    ("Microsoft Word (.docx)", "Word 文档 (.docx)"),
    ("Spreadsheet (.xlsx)", "电子表格 (.xlsx)"),
    ("Presentation (.pptx)", "演示文稿 (.pptx)"),
    ("Image (PNG)", "图片 (PNG)"),
    ("Export all images", "导出全部图片"),
    ("HTML web page", "HTML 网页"),
    ("Rich Text Format (.rtf)", "富文本文档 (.rtf)"),
    ("Text (plain)", "纯文本"),
    ("PostScript / EPS", "PostScript / EPS"),
    ("Fill", "填写"),
    ("Add text", "添加文字"),
    ("Checkmark", "勾选标记"),
    ("Cross", "叉号"),
    ("Dot", "圆点"),
    ("Line", "线条"),
    ("Date", "日期"),
    ("Signature", "签名"),
    ("Initials", "姓名缩写"),
    ("Modify page", "修改页面"),
    ("Rotate pages", "旋转页面"),
    ("Insert pages", "插入页面"),
    ("Delete pages", "删除页面"),
    ("Extract pages", "提取页面"),
    ("Add content", "添加内容"),
    ("Edit text & images", "编辑文字与图片"),
    ("Text", "文字"),
    ("Image", "图片"),
    ("Header and footer", "页眉与页脚"),
    ("Watermark", "水印"),
    ("Link", "链接"),
    ("Bates numbering", "贝茨编号"),
    ("Background", "背景"),
    ("Attach file", "添加附件"),
    ("Create from", "创建来源"),
    ("Single file", "单个文件"),
    ("Multiple files", "多个文件"),
    ("Images", "图片"),
    ("Clipboard", "剪贴板"),
    ("Blank page", "空白页面"),
    ("Combine", "合并"),
    ("Add files to combine", "添加待合并文件"),
    ("Page options", "页面选项"),
    ("Page grid", "页面网格"),
    ("Rotate", "旋转"),
    ("Extract", "提取"),
    ("Insert", "插入"),
    ("Replace", "替换"),
    ("Split", "拆分"),
    ("More", "更多"),
    ("Set page boxes", "设置页面边界"),
    ("Crop pages", "裁剪页面"),
    ("Duplicate pages", "复制页面副本"),
    ("Page labels", "页码标签"),
    ("Page transitions", "页面过渡"),
    ("Markup", "标记"),
    ("Sticky note", "便签"),
    ("Highlight text", "高亮文字"),
    ("Underline", "下划线"),
    ("Strikethrough", "删除线"),
    ("Squiggly underline", "波浪下划线"),
    ("Text box", "文本框"),
    ("Drawing", "绘制"),
    ("Draw freehand", "自由绘制"),
    ("Rectangle", "矩形"),
    ("Oval", "椭圆"),
    ("Arrow", "箭头"),
    ("Cloud", "云形"),
    ("Stamp", "印章"),
    ("Review", "审阅"),
    ("Comment list", "批注列表"),
    ("Flatten comments", "扁平化批注"),
    ("Recognize text", "识别文字"),
    ("In this file", "当前文件"),
    ("In multiple files", "多个文件"),
    ("Enhance scanned file", "增强扫描件"),
    ("Correct recognized text", "校正识别文字"),
    ("Protect", "保护"),
    ("Protect with password", "密码保护"),
    ("Remove hidden information", "移除隐藏信息"),
    ("Advanced options", "高级选项"),
    ("Encrypt with certificate", "使用证书加密"),
    ("Security properties", "安全属性"),
    ("Remove security", "移除安全设置"),
    ("Redact", "涂黑"),
    ("Redact text and images", "涂黑文字和图片"),
    ("Redact pages", "涂黑页面"),
    ("Find text and redact", "查找并涂黑文字"),
    ("Set properties", "设置属性"),
    ("Sanitize document", "清除敏感信息"),
    ("Redact all", "应用全部涂黑"),
    ("Optimize", "优化"),
    ("Reduce file size", "减小文件大小"),
    ("Advanced optimization", "高级优化"),
    ("Audit space usage", "分析空间使用"),
    ("Fields", "字段"),
    ("Field list", "字段列表"),
    ("Detect form fields", "检测表单字段"),
    ("Field properties", "字段属性"),
    ("Tab order by rows", "按行设置跳转顺序"),
    ("Tab order by columns", "按列设置跳转顺序"),
    ("Flatten form fields", "扁平化表单字段"),
    ("Import data", "导入数据"),
    ("Export data", "导出数据"),
    ("Add form components", "添加表单组件"),
    ("Text field", "文本字段"),
    ("Checkbox", "复选框"),
    ("Radio button", "单选按钮"),
    ("Drop-down list", "下拉列表"),
    ("List box", "列表框"),
    ("Button", "按钮"),
    ("Image field", "图片字段"),
    ("Date field", "日期字段"),
    ("Digital signature", "数字签名"),
    ("Stamps", "印章"),
    ("Stamp palette", "印章选择"),
    ("Certificates", "证书"),
    ("Digitally sign", "数字签名"),
    ("Timestamp", "时间戳"),
    ("Validate all signatures", "验证全部签名"),
    ("Certify (visible signature)", "认证（可见签名）"),
    ("Certify (invisible signature)", "认证（不可见签名）"),
    ("Print production", "印刷制作"),
    ("Output preview", "输出预览"),
    ("Preflight", "印前检查"),
    ("Convert colors", "转换颜色"),
    ("Add printer marks", "添加印刷标记"),
    ("Fix hairlines", "修复细线"),
    ("Measure", "测量"),
    ("Measuring tool", "测量工具"),
    ("Geospatial location", "地理位置"),
    ("Compare", "比较"),
    ("Select files to compare", "选择比较文件"),
    ("Actions list", "操作列表"),
    ("Action Wizard", "操作向导"),
    ("Make accessible", "创建无障碍文档"),
    ("Prepare for distribution", "准备分发"),
    ("Optimize scanned documents", "优化扫描文档"),
    ("Archive documents", "归档文档"),
    ("Accessibility", "辅助功能"),
    ("Automatically tag PDF", "自动标记 PDF"),
    ("Change reading options", "更改阅读选项"),
    ("Check for accessibility", "检查无障碍功能"),
    ("Open accessibility report", "打开无障碍报告"),
    ("Add alternate text", "添加替代文本"),
    ("Fix reading order", "修复阅读顺序"),
    ("Standards", "标准"),
    ("Save as PDF/A", "另存为 PDF/A"),
    ("Save as PDF/X", "另存为 PDF/X"),
    ("Save as PDF/UA", "另存为 PDF/UA"),
    ("Index", "索引"),
    ("Manage embedded index", "管理嵌入式索引"),
    ("JavaScript", "JavaScript"),
    ("Console", "控制台"),
    ("Document JavaScripts", "文档 JavaScript"),
    ("Document actions", "文档操作"),
    ("Bring your own model (off by default)", "配置自己的模型（默认关闭）"),
    ("Summarize", "总结"),
    ("Ask about this document", "询问当前文档"),
    ("Translate", "翻译"),
    ("Comments", "批注"),
    ("Bookmarks", "书签"),
    ("Form fields", "表单字段"),
    ("Layers", "图层"),
    ("Attachments", "附件"),
    ("Signatures", "签名"),
    ("Search", "搜索"),
    ("Format text", "文字格式"),
    ("Font", "字体"),
    ("Size", "大小"),
    ("Color", "颜色"),
    ("Bold", "粗体"),
    ("Italic", "斜体"),
    ("Alignment", "对齐"),
    ("Left", "左"),
    ("Center", "居中"),
    ("Right", "右"),
    ("Description", "描述"),
    ("Initial View", "初始视图"),
    ("Security", "安全"),
    ("Fonts", "字体"),
    ("Advanced", "高级"),
    ("Title", "标题"),
    ("Author", "作者"),
    ("Subject", "主题"),
    ("Keywords", "关键词"),
    ("Creator", "创建工具"),
    ("Producer", "生成工具"),
    ("Created", "创建时间"),
    ("Modified", "修改时间"),
    ("Page size", "页面尺寸"),
    ("File size", "文件大小"),
    ("Layout and Magnification", "布局与缩放"),
    ("Navigation tab", "导航标签"),
    ("Page layout", "页面布局"),
    ("Magnification", "缩放比例"),
    ("Open to page", "打开到页码"),
    ("Window Options", "窗口选项"),
    ("Resize window to initial page", "将窗口调整为初始页面大小"),
    ("Center window on screen", "将窗口居中"),
    ("Open in Full Screen mode", "以全屏模式打开"),
    ("Show:", "显示："),
    ("User Interface Options", "界面选项"),
    ("Hide menu bar", "隐藏菜单栏"),
    ("Hide toolbars", "隐藏工具栏"),
    ("Hide window controls", "隐藏窗口控件"),
    ("Revisions", "修订"),
    ("Binding", "装订"),
    ("Language", "语言"),
    ("Split document", "拆分文档"),
    ("Pages per file", "每个文件的页数"),
    ("At most", "最多"),
    ("Replace Pages", "替换页面"),
    ("Original: replace pages", "原文档：替换页面"),
    ("to", "至"),
    ("Delete pages after extracting", "提取后删除原页面"),
    ("Extract pages as separate files", "每页提取为独立文件"),
    ("Rotate Pages", "旋转页面"),
    ("Direction:", "方向："),
    ("Clockwise 90 degrees", "顺时针 90 度"),
    ("Counterclockwise 90 degrees", "逆时针 90 度"),
    ("180 degrees", "180 度"),
    ("Pages:", "页面："),
    ("Rotate:", "旋转范围："),
    ("Even and Odd Pages", "所有页面"),
    ("Even Pages Only", "仅偶数页"),
    ("Odd Pages Only", "仅奇数页"),
    ("Landscape and Portrait Pages", "横向和纵向页面"),
    ("Landscape Pages", "横向页面"),
    ("Portrait Pages", "纵向页面"),
    ("Duplicate Field", "复制字段"),
    ("Summarize Options", "批注摘要选项"),
    ("Choose a layout:", "选择布局："),
    ("Sort comments by:", "批注排序："),
    ("Number pages", "设置页码"),
    ("Style", "样式"),
    ("Prefix", "前缀"),
    ("Start", "起始值"),
    ("Recover unsaved documents?", "恢复未保存的文档？"),
    ("Recover", "恢复"),
    ("Discard", "放弃"),
    ("Don't save", "不保存"),
    ("Keyboard shortcuts", "键盘快捷键"),
    ("About", "关于"),
    ("About PrintCraft", "关于 MyAIPDF"),
    ("Your changes will be lost if you don't save them.", "如果不保存，您的修改将丢失。"),
    ("Password required", "需要密码"),
    ("Password", "密码"),
    ("Edit fields", "编辑字段"),
    ("Preview", "预览"),
    ("Dynamic", "动态"),
    ("Sign Here", "在此签名"),
    ("Standard Business", "商务标准"),
    ("Choose a stamp, then click on the page to place it.", "选择印章，再点击页面放置。"),
    ("Tab order: move a field with its arrows.", "跳转顺序：使用箭头调整字段位置。"),
    ("First page", "首页"),
    ("Previous page", "上一页"),
    ("Next page", "下一页"),
    ("Last page", "末页"),
    ("Zoom in", "放大"),
    ("Zoom out", "缩小"),
    ("Rotate view clockwise", "顺时针旋转视图"),
    ("Rotate view counterclockwise", "逆时针旋转视图"),
    ("Single page", "单页"),
    ("Continuous", "连续"),
    ("Two-up", "双页"),
    ("Select", "选择"),
    ("Hand", "手形工具"),
    ("Select text", "选择文字"),
    ("Add a note", "添加便签"),
    ("Draw", "绘制"),
    ("More options", "更多选项"),
    ("No comments", "暂无批注"),
    ("No bookmarks", "暂无书签"),
    ("No form fields", "暂无表单字段"),
    ("No attachments", "暂无附件"),
    ("No layers", "暂无图层"),
    ("No document open", "未打开文档"),
    ("Open a PDF to begin.", "打开 PDF 开始使用。"),
    ("Reply…", "回复…"),
    ("Add bookmark", "添加书签"),
    ("New bookmark", "新建书签"),
    ("Edit bookmark", "编辑书签"),
    ("Rename", "重命名"),
    ("Expand all", "全部展开"),
    ("Collapse all", "全部收起"),
    ("Properties", "属性"),
    ("Resolved", "已解决"),
    ("Open", "打开"),
    ("Download", "下载"),
    ("Export", "导出"),
    ("Add files…", "添加文件…"),
    ("Move up", "上移"),
    ("Move down", "下移"),
    ("Search text", "搜索文字"),
    ("Match case", "区分大小写"),
    ("Whole words", "全词匹配"),
    ("All pages", "所有页面"),
    ("Current page", "当前页"),
    ("Selected pages", "选定页面"),
    ("From", "从"),
    ("To", "至"),
    ("Width", "宽度"),
    ("Height", "高度"),
    ("Opacity", "不透明度"),
    ("Rotation", "旋转"),
    ("Scale", "比例"),
    ("Position", "位置"),
    ("Top", "顶部"),
    ("Bottom", "底部"),
    ("Margins", "边距"),
    ("Name", "名称"),
    ("Value", "值"),
    ("Required", "必填"),
    ("Read only", "只读"),
    ("Visible", "可见"),
    ("Hidden", "隐藏"),
    ("Options", "选项"),
    ("General", "常规"),
    ("Appearance", "外观"),
    ("Actions", "操作"),
    ("Format", "格式"),
    ("Validate", "验证"),
    ("Calculate", "计算"),
    ("No results", "没有结果"),
    ("Add a sticky note", "添加便签"),
    ("Add a text box", "添加文本框"),
    ("Underline text", "文字下划线"),
    ("Strikethrough text", "文字删除线"),
    ("Squiggly underline text", "文字波浪下划线"),
    ("Draw a line", "绘制线条"),
    ("Draw an arrow", "绘制箭头"),
    ("Draw a rectangle", "绘制矩形"),
    ("Draw an oval", "绘制椭圆"),
    ("Draw a polygon", "绘制多边形"),
    ("Draw connected lines", "绘制折线"),
    ("Draw a cloud", "绘制云形"),
    ("Add a callout", "添加引出标注"),
    ("Insert text", "插入文字"),
    ("Replace text", "替换文字"),
    ("Attach a file", "添加附件"),
    ("Erase drawings", "擦除绘图"),
    ("Import comments…", "导入批注…"),
    ("Export all comments to data file…", "导出批注数据…"),
    ("Hide all comments", "隐藏全部批注"),
    ("Summarize comments", "生成批注摘要"),
    ("Import form data…", "导入表单数据…"),
    ("Export form data…", "导出表单数据…"),
    ("PDF/A…", "PDF/A…"),
    ("Action Wizard…", "操作向导…"),
    ("Prepare for distribution…", "准备分发…"),
    ("Optimize scanned documents…", "优化扫描文档…"),
    ("Compare files…", "比较文件…"),
    ("Merge data files into spreadsheet…", "将数据文件合并为电子表格…"),
    ("Tab order: by rows", "跳转顺序：按行"),
    ("Tab order: by columns", "跳转顺序：按列"),
    ("Tab order: by document structure", "跳转顺序：按文档结构"),
    ("Add or edit links", "添加或编辑链接"),
    ("Create links from URLs", "自动识别网页链接"),
    ("Remove all links", "移除全部链接"),
    ("Add Bates numbering…", "添加贝茨编号…"),
    ("Add image…", "添加图片…"),
    ("Redact pages…", "涂黑页面…"),
    ("Find text and redact…", "查找并涂黑文字…"),
    ("Redaction properties…", "涂黑属性…"),
    ("Apply redactions…", "应用涂黑…"),
    ("Clear redaction marks", "清除涂黑标记"),
    ("Remove hidden information…", "移除隐藏信息…"),
    ("Sanitize document…", "清除敏感信息…"),
    ("Field properties…", "字段属性…"),
    ("Add a text field", "添加文本字段"),
    ("Add a checkbox", "添加复选框"),
    ("Add a radio button", "添加单选按钮"),
    ("Add a drop-down list", "添加下拉列表"),
    ("Add a list box", "添加列表框"),
    ("Add a button", "添加按钮"),
    ("Add an image field", "添加图片字段"),
    ("Add a date field", "添加日期字段"),
    ("Add a digital signature field", "添加数字签名字段"),
    ("Fill & Sign: add text", "填写与签名：添加文字"),
    ("Fill & Sign: checkmark", "填写与签名：勾号"),
    ("Fill & Sign: cross", "填写与签名：叉号"),
    ("Fill & Sign: dot", "填写与签名：圆点"),
    ("Fill & Sign: line", "填写与签名：线条"),
    ("Fill & Sign: date", "填写与签名：日期"),
    ("Fill & Sign: sign", "填写与签名：签名"),
    ("Fill & Sign: initials", "填写与签名：姓名缩写"),
    ("Export to image…", "导出为图片…"),
    ("Reduce file size…", "减小文件大小…"),
    ("Optimize PDF…", "优化 PDF…"),
    ("Export to text…", "导出为文字…"),
    ("Export to Word…", "导出为 Word…"),
    ("Export to HTML…", "导出为 HTML…"),
    ("Export to RTF…", "导出为 RTF…"),
    ("JavaScript console…", "JavaScript 控制台…"),
    ("Document JavaScripts…", "文档 JavaScript…"),
    ("Recognize text…", "识别文字…"),
    ("Recognize text in multiple files…", "批量识别文字…"),
    ("Check for accessibility…", "检查无障碍功能…"),
    ("Change reading options…", "更改阅读选项…"),
    ("Add alternate text…", "添加替代文本…"),
    ("Export all images…", "导出全部图片…"),
    ("Add header & footer…", "添加页眉与页脚…"),
    ("Update header & footer…", "更新页眉与页脚…"),
    ("Remove header & footer", "移除页眉与页脚"),
    ("Add watermark…", "添加水印…"),
    ("Update watermark…", "更新水印…"),
    ("Remove watermark", "移除水印"),
    ("Add background…", "添加背景…"),
    ("Update background…", "更新背景…"),
    ("Remove background", "移除背景"),
    ("Protect using password…", "使用密码保护…"),
    ("Security properties…", "安全属性…"),
    ("Rotate pages clockwise", "顺时针旋转页面"),
    ("Rotate pages counterclockwise", "逆时针旋转页面"),
    ("Insert blank page", "插入空白页"),
    ("Rotate pages…", "旋转页面…"),
    ("Set page boxes…", "设置页面边界…"),
    ("Insert pages from file…", "从文件插入页面…"),
    ("Replace pages…", "替换页面…"),
    ("Extract pages…", "提取页面…"),
    ("Split document…", "拆分文档…"),
    ("Number pages…", "设置页码…"),
    ("Check for updates…", "检查更新…"),
    ("Page navigation", "页面导航"),
    ("Page display", "页面显示"),
    ("No comments yet.", "暂无批注。"),
    ("No comments match.", "没有匹配的批注。"),
    ("Pick a tool in the quick bar, or type above.", "选择快捷工具，或在上方输入批注。"),
    ("Sort by", "排序方式"),
    ("Type", "类型"),
    ("Status", "状态"),
    ("Colour", "颜色"),
    ("Post", "发布"),
    ("Line thickness", "线条粗细"),
    ("Print", "打印"),
    ("Printer:", "打印机："),
    ("Copies:", "份数："),
    ("Two-sided:", "双面："),
    ("Paper:", "纸张："),
    ("More options:", "更多选项："),
    ("Pages per sheet:", "每张纸页数："),
    ("Page order:", "页面顺序："),
    ("Orientation:", "方向："),
    ("Character spacing", "字符间距"),
    ("Horizontal scale", "水平缩放"),
    ("Units", "单位"),
    ("Box", "边界"),
    ("Set Page Boxes", "设置页面边界"),
    ("Protect Using Password", "使用密码保护"),
    ("Requires user to enter a password for:", "以下操作需要输入密码："),
    ("Compatibility", "兼容性"),
    ("Encrypt", "加密"),
    ("Printing allowed", "打印权限"),
    ("Changes allowed", "修改权限"),
    ("What word or phrase would you like to search for?", "请输入要搜索的文字或短语。"),
    ("Files are combined in this order. Leave Pages empty to take every page.", "文件按此顺序合并。页面范围留空则合并全部页面。"),
    ("Resolution", "分辨率"),
    ("Quality", "质量"),
    ("Plain text in reading order; pages are separated by form feeds.", "按阅读顺序导出纯文本，页面之间用分页符分隔。"),
    ("Compare Files", "比较文件"),
    ("Old file:", "旧文件："),
    ("New file:", "新文件："),
    ("Text is compared word by word; the differences are shown on the new file.", "逐词比较文字，差异显示在新文件上。"),
    ("No differences in the text.", "文字内容没有差异。"),
    ("No actions", "暂无操作"),
    ("This document has no pages.", "此文档没有页面。"),
    ("This document has no signatures.", "此文档没有签名。"),
    ("JavaScript Console", "JavaScript 控制台"),
    ("Output appears here.", "输出将显示在此处。"),
    ("JavaScript is turned off (Preferences ▸ JavaScript).", "JavaScript 已关闭，可在偏好设置中启用。"),
    ("Recognize Text", "识别文字"),
    ("Document language", "文档语言"),
    ("Output", "输出"),
    ("Downsample to", "降低分辨率至"),
    (
        "Text recognition isn't installed: its models are missing (run `cargo xtask models`, or set PRINTCRAFT_MODELS).",
        "尚未安装文字识别模型，此功能暂不可用。",
    ),
    ("Standard fonts; text outside Windows-1252 isn't supported yet.", "此文字工具目前仅支持西文标准字体，中文文字编辑尚未支持。"),
    ("Name:", "名称："),
    ("Font:", "字体："),
    ("Font size:", "字号："),
    ("Font Size:", "字号："),
    ("Tooltip:", "提示文字："),
    ("Text Color:", "文字颜色："),
    ("Line Thickness:", "线条粗细："),
    ("Line Style:", "线条样式："),
    ("Alignment:", "对齐："),
    ("Default Value:", "默认值："),
    ("characters", "个字符"),
    ("Category:", "类别："),
    ("Location", "位置"),
    ("Reason", "原因"),
    ("Thickness", "粗细"),
    ("Total", "合计"),
    ("Welcome to MyAIPDF", "欢迎使用 MyAIPDF"),
    ("PrintCraft on GitHub", "上游 PrintCraft 源码"),
    ("E-Sign", "填写与签名"),
    ("Find tools and commands", "搜索工具和命令"),
    ("This document contains {count} interactive form fields.", "此文档包含 {count} 个可填写的表单字段。"),
    ("Highlight fields", "高亮字段"),
    ("Hide field highlights", "隐藏字段高亮"),
    ("Page thumbnails", "页面缩略图"),
    ("Save (M4)", "保存（⌘S）"),
    ("Print (⌘P)", "打印（⌘P）"),
    ("Document properties", "文档属性"),
    ("Previous view", "上一视图"),
    ("Next view", "下一视图"),
    ("Page only", "仅页面"),
    ("Page and bookmarks", "页面与书签"),
    ("Page and thumbnails", "页面与缩略图"),
    ("Single Page", "单页"),
    ("One Column", "单列连续"),
    ("Two-Up (Facing)", "双页并排"),
    ("Two-Up (Cover Page)", "双页（封面独立）"),
    ("Default", "默认"),
    ("Viewing", "阅读"),
    ("Editing", "编辑"),
    ("Type Password", "输入密码"),
    ("Re-type Password", "再次输入密码"),
    ("All document contents", "全部文档内容"),
    ("All document contents except metadata", "除元数据外的全部内容"),
];

#[cfg(test)]
mod tests {
    use crate::i18n::Language;

    #[test]
    fn chinese_strings_are_unique_and_catalog_is_translated() {
        for (i, (en, zh)) in super::CHINESE.iter().enumerate() {
            assert!(!zh.is_empty());
            assert!(super::CHINESE[..i].iter().all(|(other, _)| en != other), "duplicate: {en}");
        }
        for group in printcraft_engine::catalog::TOOL_GROUPS {
            assert_ne!(Language::Zh.tr(group.label), group.label, "{}", group.label);
        }
        assert_eq!(Language::Zh.tr("客户合同.pdf"), "客户合同.pdf");
        assert_eq!(Language::parse("zh-cn"), Some(Language::Zh));
    }
}
