#!/usr/bin/env bash
# Package already-tested native binaries. Never replaces an existing output.
set -euo pipefail
MYAI_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
MYAI_OUTPUT="${1:?Usage: bash packaging/macos/myaipdf.sh /absolute/path/MyAIPDF.dmg}"
case "$MYAI_OUTPUT" in /*.dmg) ;; *) echo "Output must be an absolute .dmg path" >&2; exit 2 ;; esac
if [ -e "$MYAI_OUTPUT" ] || [ -L "$MYAI_OUTPUT" ]; then echo "Refusing to overwrite: $MYAI_OUTPUT" >&2; exit 2; fi
test -x "$MYAI_ROOT/target/release/printcraft"
test -x "$MYAI_ROOT/target/release/printcraft-cli"
test -x "$MYAI_ROOT/target/release/myaipdf-updater"
test -f "$MYAI_ROOT/assets/models/text-detection.rten"
test -f "$MYAI_ROOT/assets/models/text-recognition.rten"
MYAI_WORK="$(mktemp -d "$MYAI_ROOT/target/myaipdf-package.XXXXXX")"
MYAI_STAGE="$MYAI_WORK/image"
MYAI_APP="$MYAI_STAGE/MyAIPDF.app"
mkdir -p "$MYAI_APP/Contents/MacOS" "$MYAI_APP/Contents/Resources/Licenses"
cp "$MYAI_ROOT/target/release/printcraft" "$MYAI_APP/Contents/MacOS/MyAIPDF"
cp "$MYAI_ROOT/target/release/printcraft-cli" "$MYAI_APP/Contents/MacOS/myaipdf-cli"
cp "$MYAI_ROOT/target/release/myaipdf-updater" "$MYAI_APP/Contents/MacOS/myaipdf-updater"
cp "$MYAI_ROOT/packaging/macos/MyAIPDF-Info.plist" "$MYAI_APP/Contents/Info.plist"
cp "$MYAI_ROOT/assets/myaipdf/MyAIPDF.icns" "$MYAI_APP/Contents/Resources/"
cp "$MYAI_ROOT/ATTRIBUTION.md" "$MYAI_APP/Contents/Resources/"
cp "$MYAI_ROOT/packaging/macos/MyAIPDF-使用说明.txt" "$MYAI_APP/Contents/Resources/使用说明.txt"
cp "$MYAI_ROOT/packaging/macos/MyAIPDF-使用说明.txt" "$MYAI_STAGE/使用说明.txt"
cp "$MYAI_ROOT/LICENSE-MIT" "$MYAI_ROOT/LICENSE-APACHE" "$MYAI_ROOT/NOTICE" "$MYAI_APP/Contents/Resources/Licenses/"
mkdir -p "$MYAI_APP/Contents/Resources/models"
cp "$MYAI_ROOT/assets/models/"*.rten "$MYAI_ROOT/assets/models/"*.LICENCE.txt "$MYAI_APP/Contents/Resources/models/"
while IFS= read -r MYAI_LICENSE; do
    MYAI_REL="${MYAI_LICENSE#"$MYAI_ROOT/"}"
    mkdir -p "$MYAI_APP/Contents/Resources/Licenses/$(dirname "$MYAI_REL")"
    cp "$MYAI_LICENSE" "$MYAI_APP/Contents/Resources/Licenses/$MYAI_REL"
done < <(find "$MYAI_ROOT/assets" "$MYAI_ROOT/vendor" "$MYAI_ROOT/craft-fonts/fonts" -type f \( -iname '*license*' -o -iname '*licence*' -o -iname '*ofl*' \))
ln -s /Applications "$MYAI_STAGE/Applications"
plutil -lint "$MYAI_APP/Contents/Info.plist"
codesign --force --sign - --timestamp=none "$MYAI_APP/Contents/MacOS/myaipdf-cli"
codesign --force --sign - --timestamp=none "$MYAI_APP/Contents/MacOS/myaipdf-updater"
codesign --force --sign - --timestamp=none "$MYAI_APP/Contents/MacOS/MyAIPDF"
codesign --force --sign - --timestamp=none "$MYAI_APP"
codesign --verify --strict --deep --verbose=2 "$MYAI_APP"
file "$MYAI_APP/Contents/MacOS/MyAIPDF"
# APFS preserves the signed bundle without makehybrid's empty FinderInfo attributes.
hdiutil create -srcfolder "$MYAI_STAGE" -fs APFS -volname "MyAIPDF" -format UDZO -imagekey zlib-level=9 "$MYAI_WORK/MyAIPDF.dmg"
codesign --force --sign - --timestamp=none "$MYAI_WORK/MyAIPDF.dmg"
hdiutil verify "$MYAI_WORK/MyAIPDF.dmg"
codesign --verify --strict --verbose=2 "$MYAI_WORK/MyAIPDF.dmg"
mv -n "$MYAI_WORK/MyAIPDF.dmg" "$MYAI_OUTPUT"
shasum -a 256 "$MYAI_OUTPUT"
echo "Application staging: $MYAI_APP"
echo "DMG: $MYAI_OUTPUT"
