//! Reproducible independent font input. No font binaries enter the product repository.
use anyhow::Result;
const IBM: &str = "https://raw.githubusercontent.com/IBM/plex/763c36ef9117782905ae010056dfbe8fd2653a25/packages/plex-sans-sc";
const CRAFT: &str = "https://raw.githubusercontent.com/storytold/craft-fonts/abb83316d96aa59c1cf64784289e378fe9fa5695";
const ARABIC: &str = "https://raw.githubusercontent.com/google/fonts/7085eb89a950e85db5b166b7a58d414544b4140c/ofl/notosansarabic";
const OTHER: &[(&str, &str, &str, &str, &str)] = &[
    (
        "Shippori Mincho",
        "Regular",
        "fonts/shippori-mincho/ShipporiMincho-Regular.ttf",
        "Jpan,Latn",
        "769b5269f0f9bc6534b352c0e6bd856a566e03ff788f107191c2d835863570b2",
    ),
    (
        "BIZ UDPGothic",
        "Regular",
        "fonts/biz-ud-pgothic/BIZUDPGothic-Regular.ttf",
        "Jpan,Latn",
        "258d7156c165f2ff774b6efee637c22c3b950de0d8a10e501137061bc8085d01",
    ),
    (
        "BIZ UDPGothic",
        "Bold",
        "fonts/biz-ud-pgothic/BIZUDPGothic-Bold.ttf",
        "Jpan,Latn",
        "30eba52fc837e8b62c97d4b82e6706583149fb7294e3712dd71a655eaea80a90",
    ),
    (
        "BIZ UDMincho",
        "Regular",
        "fonts/biz-ud-mincho/BIZUDMincho-Regular.ttf",
        "Jpan,Latn",
        "468ee6d9b149ca144809e03841bf18740ecf014e055a00da6ecaf1aaf4165af2",
    ),
    (
        "Noto Sans Arabic",
        "Regular",
        "fonts/noto-sans-arabic/NotoSansArabic.ttf",
        "Arab",
        "63111b5b2e074dd48cc67692e0a2726d86ee94c1c37fe8598257b7b4e87e869e",
    ),
];
const LICENSES: &[(&str, &str)] = &[
    ("fonts/shippori-mincho/OFL.txt", "41fba056279be5f45ff9a99e44b7b53897b42732f5806d8e666e0ab49ac6bd38"),
    ("fonts/biz-ud-pgothic/OFL.txt", "e753d7155d53c747d037a445e584c8ecfca6dd79846db610417e282a736b28bc"),
    ("fonts/biz-ud-mincho/OFL.txt", "ef0ed524b3bd012f37015e986809eed6f67905456ebfc1ebd7fcc2765282ee01"),
    ("fonts/noto-sans-arabic/OFL.txt", "07fc70bfeb985cc1a87a8587d0a0c80bab11c86c9dc3fd95b6f0cb332f983e96"),
];
const CHINESE: &[(&str, &str)] = &[
    ("Regular", "012e587c5a78d25f456057614b880fc7450b748c352573d8052245df2a71158a"),
    ("Medium", "6e6a084fd3f43c2c6f6d662cbc4c7b09987bafd928c43e91c8e8f68c6ae01e31"),
    ("SemiBold", "76706e94340ac068ec2d398dc2f387946c815a3610f35c41cc93a8f8097d6c6b"),
];
pub fn run(args: &[String]) -> Result<()> {
    let root = args.first().map(std::path::PathBuf::from).unwrap_or_else(|| crate::gates::root().join("craft-fonts"));
    std::fs::create_dir_all(root.join("fonts/ibm-plex-sans-sc"))?;
    let mut manifest = String::from("# MyAIPDF independent OFL font build input, generated by cargo xtask myaipdf-fonts.\n");
    let mut attribution = String::from(
        "# MyAIPDF font build input\n\nIBM Plex: IBM Corp, reserved font name Plex, OFL-1.1. Japanese and Arabic authorship and required notices: pinned storytold/craft-fonts. Font files unchanged; all files and licences SHA-256 verified. No Source Han or Noto CJK.\n\n",
    );
    for (family, style, file, scripts, hash) in OTHER {
        let target = root.join(file);
        let parent = target.parent().ok_or_else(|| anyhow::anyhow!("missing font directory"))?;
        std::fs::create_dir_all(parent)?;
        let url = if *family == "Noto Sans Arabic" { format!("{ARABIC}/NotoSansArabic%5Bwdth%2Cwght%5D.ttf") } else { format!("{CRAFT}/{file}") };
        crate::assets::fetch_verified(&url, &target, hash)?;
        let license = parent.join("OFL.txt");
        let relative = license.strip_prefix(&root)?.to_string_lossy();
        manifest.push_str(&format!("{family} | {style} | {file} | {scripts} | OFL-1.1 | {relative} | {hash} | {url}\n"));
        attribution.push_str(&format!("- {family} {style}: {url}, SHA-256 {hash}, OFL-1.1.\n"));
    }
    for (file, hash) in LICENSES {
        let url = if file.starts_with("fonts/noto-sans-arabic/") { format!("{ARABIC}/OFL.txt") } else { format!("{CRAFT}/{file}") };
        crate::assets::fetch_verified(&url, &root.join(file), hash)?;
    }
    crate::assets::fetch_verified(
        &format!("{IBM}/LICENSE.txt"),
        &root.join("fonts/ibm-plex-sans-sc/OFL.txt"),
        "7e6b2818edbd8f6a01ae80641cc8f16a51080d08fb4e532be3a0b6f74adb07da",
    )?;
    for (style, hash) in CHINESE {
        let file = format!("fonts/ibm-plex-sans-sc/IBMPlexSansSC-{style}.ttf");
        let url = format!("{IBM}/fonts/complete/ttf/hinted/IBMPlexSansSC-{style}.ttf");
        crate::assets::fetch_verified(&url, &root.join(&file), hash)?;
        manifest.push_str(&format!("IBM Plex Sans SC | {style} | {file} | Hans,Latn | OFL-1.1 | fonts/ibm-plex-sans-sc/OFL.txt | {hash} | {url}\n"));
        attribution.push_str(&format!("- IBM Plex Sans SC {style}: {url}, SHA-256 {hash}, OFL-1.1.\n"));
    }
    std::fs::write(root.join("fonts/manifest.txt"), manifest)?;
    std::fs::write(root.join("ATTRIBUTION.md"), attribution)?;
    println!("MyAIPDF font input: {} (set CRAFT_FONTS_DIR to this absolute path)", root.display());
    Ok(())
}
